// ─────────────────────────────────────────────────────────────
//  Export Controller — CSV & PDF Report Generation
// ─────────────────────────────────────────────────────────────
const Lead = require("../models/Lead");
const Deal = require("../models/Deal");
const { Parser } = require("json2csv");
const PDFDocument = require("pdfkit");

// ── @route  GET /api/export/leads/csv ─────────────────────────
const exportLeadsCSV = async (req, res, next) => {
  try {
    const leads = await Lead.find()
      .populate("assignedTo", "name")
      .populate("createdBy", "name")
      .lean();

    const fields = [
      { label: "Name", value: "name" },
      { label: "Email", value: "email" },
      { label: "Company", value: "company" },
      { label: "Budget", value: "budget" },
      { label: "Company Size", value: "companySize" },
      { label: "AI Score", value: "leadScore" },
      { label: "Category", value: "leadCategory" },
      { label: "Status", value: "status" },
      { label: "Source", value: "source" },
      { label: "Assigned To", value: "assignedTo.name" },
      { label: "Created At", value: "createdAt" },
    ];

    const parser = new Parser({ fields });
    const csv = parser.parse(leads);

    res.header("Content-Type", "text/csv");
    res.header("Content-Disposition", "attachment; filename=leads.csv");
    res.send(csv);
  } catch (error) {
    next(error);
  }
};

// ── @route  GET /api/export/deals/csv ─────────────────────────
const exportDealsCSV = async (req, res, next) => {
  try {
    const deals = await Deal.find()
      .populate("assignedTo", "name")
      .populate("customer", "name")
      .lean();

    const fields = [
      { label: "Title", value: "title" },
      { label: "Value", value: "value" },
      { label: "Currency", value: "currency" },
      { label: "Stage", value: "stage" },
      { label: "AI Probability", value: "dealProbability" },
      { label: "Status", value: "dealPredictionStatus" },
      { label: "Days in Pipeline", value: "daysInPipeline" },
      { label: "Budget Confirmed", value: "hasBudgetConfirmed" },
      { label: "Has Champion", value: "hasChampion" },
      { label: "Customer", value: "customer.name" },
      { label: "Assigned To", value: "assignedTo.name" },
      { label: "Close Date", value: "closeDate" },
      { label: "Created At", value: "createdAt" },
    ];

    const parser = new Parser({ fields });
    const csv = parser.parse(deals);

    res.header("Content-Type", "text/csv");
    res.header("Content-Disposition", "attachment; filename=deals.csv");
    res.send(csv);
  } catch (error) {
    next(error);
  }
};

// ── @route  GET /api/export/analytics/pdf ─────────────────────
const exportAnalyticsPDF = async (req, res, next) => {
  try {
    // Fetch summary data
    const [totalLeads, totalDeals, totalRevenue] = await Promise.all([
      Lead.countDocuments(),
      Deal.countDocuments(),
      Deal.aggregate([
        { $match: { stage: "Closed Won" } },
        { $group: { _id: null, total: { $sum: "$value" } } },
      ]),
    ]);

    const topLeads = await Lead.find().sort({ leadScore: -1 }).limit(10).select("name company leadScore");

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });

    res.header("Content-Type", "application/pdf");
    res.header("Content-Disposition", "attachment; filename=analytics-report.pdf");

    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor("#00d4ff").text("AI SaaS CRM", { align: "center" });
    doc.fontSize(16).fillColor("#000000").text("Analytics Report", { align: "center" });
    doc.moveDown();
    doc.fontSize(10).fillColor("#666666").text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(2);

    // Overview Section
    doc.fontSize(18).fillColor("#000000").text("Overview", { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    doc.text(`Total Leads: ${totalLeads}`);
    doc.text(`Total Deals: ${totalDeals}`);
    doc.text(`Total Revenue: $${(totalRevenue[0]?.total || 0).toLocaleString()}`);
    doc.moveDown(2);

    // Top Leads Section
    doc.fontSize(18).text("Top 10 Leads by AI Score", { underline: true });
    doc.moveDown();
    doc.fontSize(10);

    topLeads.forEach((lead, i) => {
      doc.text(`${i + 1}. ${lead.name} (${lead.company || "N/A"}) - Score: ${lead.leadScore}`);
    });

    doc.moveDown(2);

    // Footer
    doc.fontSize(8).fillColor("#999999").text(
      "This report was generated by AI SaaS CRM System",
      50,
      doc.page.height - 50,
      { align: "center" }
    );

    doc.end();
  } catch (error) {
    next(error);
  }
};

module.exports = { exportLeadsCSV, exportDealsCSV, exportAnalyticsPDF };
